export default [
  { path: '/', redirect: '/admin/user' },
  {
    name: '用户管理',
    path: '/admin/user',
    component: './Admin/UserList',
    icon: 'UserOutlined',
    access: 'canAdmin',
  },
  {
    name: '帖子管理',
    path: '/admin/post',
    component: './Admin/PostList',
    icon: 'TableOutlined',
    access: 'canAdmin',
  },
  {
    name: '评论管理',
    path: '/admin/comment',
    component: './Admin/CommentList',
    icon: 'MessageOutlined',
    access: 'canAdmin',
  },
  {
    name: '通知管理',
    path: '/admin/notification',
    component: './Admin/NotificationList',
    icon: 'NotificationOutlined',
    access: 'canAdmin',
  },
  {
    name: '微信管理',
    path: '/admin/wechat',
    component: './Admin/WeChat',
    icon: 'WechatOutlined',
    access: 'canAdmin',
  },
  {
    name: '邮件工具',
    path: '/admin/mail',
    component: './Admin/MailTool',
    icon: 'MailOutlined',
    access: 'canAdmin',
  },
  {
    name: '聚合搜索',
    path: '/admin/search',
    component: './Admin/SearchCenter',
    icon: 'SearchOutlined',
    access: 'canAdmin',
  },
  {
    path: '/user',
    layout: false,
    routes: [{ name: '用户登录', path: '/user/login', component: './User/Login' }],
  },
  {
    name: 'exception',
    icon: 'warning',
    path: '/exception',
    layout: false,
    routes: [
      {
        path: '/exception',
        redirect: '/exception/403',
      },
      {
        name: '403',
        icon: 'smile',
        path: '/exception/403',
        component: './Exception/403',
      },
      {
        name: '404',
        icon: 'smile',
        path: '/exception/404',
        component: './Exception/404',
      },
      {
        name: '500',
        icon: 'smile',
        path: '/exception/500',
        component: './Exception/500',
      },
    ],
  },
  { path: '*', layout: false, component: './Exception/404' },
];
